"""W3C PROV-DM provenance module for NOVA.

Implements provenance tracking based on the W3C PROV Data Model,
serialized as JSON-LD. Provenance is REQUIRED for reduced/calibrated
data (INV-5: PROV_MANDATORY).
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from typing import Any

NOVA_CONTEXT = "https://nova-astro.org/v0.1/context.jsonld"
PROV_CONTEXT = "https://www.w3.org/ns/prov"


@dataclass
class ProvenanceEntity:
    """A data entity in the provenance chain.

    Parameters
    ----------
    entity_id : str
        Unique identifier (URI or CURIE).
    entity_type : str
        Entity type (default: 'prov:Entity').
    data_level : str
        NOVA data level ('L0', 'L1', 'L2', 'L3').
    filename : str
        Original filename.
    data_format : str
        Data format ('NOVA', 'FITS').
    content_hash : str
        SHA-256 content hash.
    derived_from : str or None
        Entity ID this was derived from.
    generated_by : str or None
        Activity ID that generated this entity.
    """

    entity_id: str
    entity_type: str = "prov:Entity"
    data_level: str = ""
    filename: str = ""
    data_format: str = ""
    content_hash: str = ""
    derived_from: str | None = None
    generated_by: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to JSON-LD dictionary."""
        d: dict[str, Any] = {
            "@id": self.entity_id,
            "@type": self.entity_type,
        }
        if self.data_level:
            d["nova:data_level"] = self.data_level
        if self.filename:
            d["nova:filename"] = self.filename
        if self.data_format:
            d["nova:format"] = self.data_format
        if self.content_hash:
            d["nova:content_hash"] = self.content_hash
        if self.derived_from:
            d["prov:wasDerivedFrom"] = {"@id": self.derived_from}
        if self.generated_by:
            d["prov:wasGeneratedBy"] = {"@id": self.generated_by}
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProvenanceEntity:
        """Create from JSON-LD dictionary."""
        derived_from = None
        if "prov:wasDerivedFrom" in data:
            df = data["prov:wasDerivedFrom"]
            derived_from = df["@id"] if isinstance(df, dict) else str(df)

        generated_by = None
        if "prov:wasGeneratedBy" in data:
            gb = data["prov:wasGeneratedBy"]
            generated_by = gb["@id"] if isinstance(gb, dict) else str(gb)

        return cls(
            entity_id=data["@id"],
            entity_type=data.get("@type", "prov:Entity"),
            data_level=data.get("nova:data_level", ""),
            filename=data.get("nova:filename", ""),
            data_format=data.get("nova:format", ""),
            content_hash=data.get("nova:content_hash", ""),
            derived_from=derived_from,
            generated_by=generated_by,
        )


@dataclass
class ProvenanceActivity:
    """A processing activity in the provenance chain.

    Parameters
    ----------
    activity_id : str
        Unique identifier.
    activity_type : str
        Activity type (default: 'prov:Activity').
    started_at : str
        ISO 8601 start time.
    ended_at : str
        ISO 8601 end time.
    used : list of str
        Entity IDs used by this activity.
    generated : list of str
        Entity IDs generated by this activity.
    software : str
        Software name and version.
    algorithm : str
        Algorithm name.
    parameters : dict
        Processing parameters.
    """

    activity_id: str
    activity_type: str = "prov:Activity"
    started_at: str = ""
    ended_at: str = ""
    used: list[str] = field(default_factory=list)
    generated: list[str] = field(default_factory=list)
    software: str = ""
    algorithm: str = ""
    parameters: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to JSON-LD dictionary."""
        d: dict[str, Any] = {
            "@id": self.activity_id,
            "@type": self.activity_type,
        }
        if self.started_at:
            d["prov:startedAtTime"] = self.started_at
        if self.ended_at:
            d["prov:endedAtTime"] = self.ended_at
        if self.used:
            if len(self.used) == 1:
                d["prov:used"] = {"@id": self.used[0]}
            else:
                d["prov:used"] = [{"@id": uid} for uid in self.used]
        if self.generated:
            if len(self.generated) == 1:
                d["prov:generated"] = {"@id": self.generated[0]}
            else:
                d["prov:generated"] = [{"@id": gid} for gid in self.generated]
        if self.software:
            d["nova:software"] = self.software
        if self.algorithm:
            d["nova:algorithm"] = self.algorithm
        if self.parameters:
            d["nova:parameters"] = self.parameters
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProvenanceActivity:
        """Create from JSON-LD dictionary."""
        used: list[str] = []
        if "prov:used" in data:
            u = data["prov:used"]
            if isinstance(u, list):
                used = [item["@id"] if isinstance(item, dict) else str(item) for item in u]
            elif isinstance(u, dict):
                used = [u["@id"]]
            else:
                used = [str(u)]

        generated: list[str] = []
        if "prov:generated" in data:
            g = data["prov:generated"]
            if isinstance(g, list):
                generated = [item["@id"] if isinstance(item, dict) else str(item) for item in g]
            elif isinstance(g, dict):
                generated = [g["@id"]]
            else:
                generated = [str(g)]

        return cls(
            activity_id=data["@id"],
            activity_type=data.get("@type", "prov:Activity"),
            started_at=data.get("prov:startedAtTime", ""),
            ended_at=data.get("prov:endedAtTime", ""),
            used=used,
            generated=generated,
            software=data.get("nova:software", ""),
            algorithm=data.get("nova:algorithm", ""),
            parameters=data.get("nova:parameters", {}),
        )


@dataclass
class ProvenanceAgent:
    """An agent in the provenance chain.

    Parameters
    ----------
    agent_id : str
        Unique identifier.
    agent_type : str
        Agent type ('prov:SoftwareAgent', 'prov:Person', 'prov:Organization').
    name : str
        Agent name.
    version : str
        Software version (for SoftwareAgent).
    """

    agent_id: str
    agent_type: str = "prov:SoftwareAgent"
    name: str = ""
    version: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to JSON-LD dictionary."""
        d: dict[str, Any] = {
            "@id": self.agent_id,
            "@type": self.agent_type,
        }
        if self.name:
            d["nova:name"] = self.name
        if self.version:
            d["nova:version"] = self.version
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProvenanceAgent:
        """Create from JSON-LD dictionary."""
        return cls(
            agent_id=data["@id"],
            agent_type=data.get("@type", "prov:SoftwareAgent"),
            name=data.get("nova:name", ""),
            version=data.get("nova:version", ""),
        )


@dataclass
class ProvenanceBundle:
    """A W3C PROV-DM bundle containing provenance metadata.

    Parameters
    ----------
    entities : list of ProvenanceEntity
        Data entities.
    activities : list of ProvenanceActivity
        Processing activities.
    agents : list of ProvenanceAgent
        Agents involved in processing.
    """

    entities: list[ProvenanceEntity] = field(default_factory=list)
    activities: list[ProvenanceActivity] = field(default_factory=list)
    agents: list[ProvenanceAgent] = field(default_factory=list)

    def add_entity(self, entity: ProvenanceEntity) -> None:
        """Add an entity to the provenance bundle."""
        self.entities.append(entity)

    def add_activity(self, activity: ProvenanceActivity) -> None:
        """Add an activity to the provenance bundle."""
        self.activities.append(activity)

    def add_agent(self, agent: ProvenanceAgent) -> None:
        """Add an agent to the provenance bundle."""
        self.agents.append(agent)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to JSON-LD dictionary.

        Returns
        -------
        dict
            W3C PROV-DM bundle as JSON-LD.
        """
        d: dict[str, Any] = {
            "@context": [NOVA_CONTEXT, PROV_CONTEXT],
            "@type": "prov:Bundle",
        }
        if self.entities:
            d["prov:entity"] = [e.to_dict() for e in self.entities]
        if self.activities:
            d["prov:activity"] = [a.to_dict() for a in self.activities]
        if self.agents:
            d["prov:agent"] = [a.to_dict() for a in self.agents]
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProvenanceBundle:
        """Create from JSON-LD dictionary.

        Parameters
        ----------
        data : dict
            W3C PROV-DM bundle as JSON-LD.

        Returns
        -------
        ProvenanceBundle
            Parsed provenance bundle.
        """
        entities = [
            ProvenanceEntity.from_dict(e)
            for e in data.get("prov:entity", [])
        ]
        activities = [
            ProvenanceActivity.from_dict(a)
            for a in data.get("prov:activity", [])
        ]
        agents = [
            ProvenanceAgent.from_dict(a)
            for a in data.get("prov:agent", [])
        ]
        return cls(
            entities=entities,
            activities=activities,
            agents=agents,
        )

    def validate(self, data_level: str) -> list[str]:
        """Validate the provenance bundle.

        Parameters
        ----------
        data_level : str
            NOVA data level ('L0', 'L1', 'L2', 'L3').

        Returns
        -------
        list of str
            Validation errors. Empty list means valid.
        """
        errors: list[str] = []

        if data_level in ("L1", "L2", "L3"):
            if not self.entities:
                errors.append(
                    f"Data level {data_level} requires at least one "
                    f"provenance entity (INV-5: PROV_MANDATORY)."
                )
            if not self.activities:
                errors.append(
                    f"Data level {data_level} requires at least one "
                    f"provenance activity (INV-5: PROV_MANDATORY)."
                )

        # Check entity references
        entity_ids = {e.entity_id for e in self.entities}
        for activity in self.activities:
            for used_id in activity.used:
                if used_id not in entity_ids:
                    errors.append(
                        f"Activity '{activity.activity_id}' references "
                        f"unknown entity '{used_id}'."
                    )
            for gen_id in activity.generated:
                if gen_id not in entity_ids:
                    errors.append(
                        f"Activity '{activity.activity_id}' references "
                        f"unknown generated entity '{gen_id}'."
                    )

        return errors
