"""Tutorial 02: FITS<->NOVA Conversion -- Migrating from FITS to NOVA.

This step-by-step tutorial demonstrates how to:
  1. Create a realistic FITS file with WCS and header keywords
  2. Convert FITS -> NOVA (preserving all metadata)
  3. Inspect the NOVA dataset and its JSON-LD metadata
  4. Convert NOVA -> FITS (lossless round-trip)
  5. Verify round-trip fidelity

Run:
    cd nova-py
    python tutorials/02_fits_conversion.py
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

import numpy as np


def main() -> None:
    """Run the FITS conversion tutorial."""
    try:
        from astropy.io import fits as astropy_fits
    except ImportError:
        print("ERROR: astropy is required. Install with: pip install astropy")
        return

    from nova.fits_converter import from_fits, to_fits
    from nova.container import NovaDataset

    print("=" * 70)
    print("  FITS <-> NOVA Conversion Tutorial")
    print("  Migrating astronomical data from FITS to NOVA and back")
    print("=" * 70)
    print()

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # -- Step 1: Create a realistic FITS file --------------------------
        print("Step 1: Create a realistic FITS file with WCS metadata")
        print("-" * 70)

        rng = np.random.default_rng(12345)
        data = rng.normal(1000.0, 50.0, (2048, 2048)).astype(np.float32)

        header = astropy_fits.Header()
        # WCS keywords
        header["WCSAXES"] = 2
        header["CTYPE1"] = "RA---TAN"
        header["CTYPE2"] = "DEC--TAN"
        header["CRPIX1"] = 1024.0
        header["CRPIX2"] = 1024.0
        header["CRVAL1"] = 83.633083  # Orion Nebula RA
        header["CRVAL2"] = -5.375278  # Orion Nebula Dec
        header["CD1_1"] = -5.556e-05
        header["CD1_2"] = 0.0
        header["CD2_1"] = 0.0
        header["CD2_2"] = 5.556e-05
        header["CUNIT1"] = "deg"
        header["CUNIT2"] = "deg"
        header["RADESYS"] = "ICRS"
        header["EQUINOX"] = 2000.0
        # Observation metadata
        header["TELESCOP"] = "VLT-UT1"
        header["INSTRUME"] = "FORS2"
        header["OBJECT"] = "M42 - Orion Nebula"
        header["FILTER"] = "V_BESS"
        header["EXPTIME"] = 300.0
        header["DATE-OBS"] = "2024-01-15T03:22:45"
        header["OBSERVER"] = "Tutorial Demo"
        header["BUNIT"] = "ADU"
        header.add_comment("Example FITS file for NOVA tutorial")
        header.add_history("Generated by tutorial 02_fits_conversion.py")

        fits_path = tmpdir / "m42_observation.fits"
        hdu = astropy_fits.PrimaryHDU(data=data, header=header)
        hdul = astropy_fits.HDUList([hdu])
        hdul.writeto(str(fits_path), overwrite=True)

        fits_size = fits_path.stat().st_size
        print(f"  File:        {fits_path.name}")
        print(f"  Object:      M42 - Orion Nebula")
        print(f"  Shape:       {data.shape}")
        print(f"  Dtype:       {data.dtype}")
        print(f"  Size:        {fits_size / (1024*1024):.1f} MB")
        print(f"  WCS:         TAN projection, ICRS frame")
        print(f"  Instrument:  VLT/FORS2")
        print()

        # -- Step 2: Convert FITS -> NOVA -----------------------------------
        print("Step 2: Convert FITS -> NOVA format")
        print("-" * 70)

        nova_path = tmpdir / "m42_observation.nova.zarr"
        ds = from_fits(fits_path, nova_path)

        nova_size = sum(
            f.stat().st_size for f in nova_path.rglob("*") if f.is_file()
        )
        print(f"  Output:      {nova_path.name}")
        print(f"  Size:        {nova_size / (1024*1024):.1f} MB")
        print(f"  Compression: {data.nbytes / nova_size:.1f}x")
        print(f"  OK Conversion complete!")
        ds.close()
        print()

        # -- Step 3: Inspect NOVA metadata ---------------------------------
        print("Step 3: Inspect the NOVA dataset and JSON-LD metadata")
        print("-" * 70)

        ds = NovaDataset(nova_path, mode="r")
        print(f"  Data shape:  {ds.data.shape}")  # type: ignore[union-attr]
        print(f"  WCS proj:    {ds.wcs.projection.code}")  # type: ignore[union-attr]
        print(f"  WCS frame:   {ds.wcs.celestial_frame.system}")  # type: ignore[union-attr]
        print(f"  Pixel scale: {ds.wcs.transform.pixel_scale} arcsec/pixel")
        print()

        # Show JSON-LD metadata
        meta_path = nova_path / "nova_metadata.json"
        with open(meta_path) as f:
            meta = json.load(f)

        print("  JSON-LD Metadata (excerpt):")
        print(f"    @context: {meta['@context']}")
        print(f"    @type:    {meta['@type']}")
        print(f"    version:  {meta['nova:version']}")
        keywords = meta.get("nova:keywords", {})
        print(f"    TELESCOP: {keywords.get('TELESCOP', 'N/A')}")
        print(f"    INSTRUME: {keywords.get('INSTRUME', 'N/A')}")
        print(f"    OBJECT:   {keywords.get('OBJECT', 'N/A')}")
        print(f"    EXPTIME:  {keywords.get('EXPTIME', 'N/A')} s")
        print()

        # Show WCS JSON-LD
        wcs_path = nova_path / "wcs.json"
        with open(wcs_path) as f:
            wcs_json = json.load(f)
        print("  WCS JSON-LD (structured, typed, validatable):")
        print(f"    {json.dumps(wcs_json, indent=4)[:500]}...")
        print()

        # Show provenance
        prov_path = nova_path / "provenance.json"
        if prov_path.exists():
            with open(prov_path) as f:
                prov = json.load(f)
            print("  Provenance (W3C PROV-DM):")
            activities = prov.get("prov:activity", [])
            for act in activities:
                print(f"    Activity: {act['@id']}")
                print(f"    Software: {act.get('nova:software', 'N/A')}")
        print()

        ds.close()

        # -- Step 4: Convert NOVA -> FITS (round-trip) ---------------------
        print("Step 4: Convert NOVA -> FITS (round-trip)")
        print("-" * 70)

        roundtrip_path = tmpdir / "m42_roundtrip.fits"
        to_fits(nova_path, roundtrip_path, overwrite=True)

        rt_size = roundtrip_path.stat().st_size
        print(f"  Output:      {roundtrip_path.name}")
        print(f"  Size:        {rt_size / (1024*1024):.1f} MB")
        print()

        # -- Step 5: Verify round-trip fidelity ----------------------------
        print("Step 5: Verify lossless round-trip fidelity (INV-1)")
        print("-" * 70)

        with astropy_fits.open(str(roundtrip_path)) as hdul_rt:
            rt_data = hdul_rt[0].data
            rt_header = hdul_rt[0].header

        # Compare data
        # Original was float32 -> big-endian in FITS -> we compare values
        original_data = data.astype(">f4")  # Match FITS endianness
        max_diff = np.max(np.abs(rt_data.astype(np.float64) - original_data.astype(np.float64)))
        print(f"  Max data diff:  {max_diff}")
        print(f"  Data match:     {'OK PASS' if max_diff == 0 else 'FAIL FAIL'}")

        # Compare WCS keywords
        wcs_match = True
        for key in ["CTYPE1", "CTYPE2", "CRPIX1", "CRPIX2", "CRVAL1", "CRVAL2"]:
            orig = header.get(key)
            rt = rt_header.get(key)
            match = orig == rt
            if not match:
                wcs_match = False
            symbol = "OK" if match else "FAIL"
            print(f"  {key:8s}:     {symbol} (original={orig}, roundtrip={rt})")

        print()
        if max_diff == 0 and wcs_match:
            print("  OK LOSSLESS ROUND-TRIP VERIFIED (INV-1: BACKWARD_COMPAT)")
        else:
            print("  ? Round-trip has minor differences (expected for float precision)")

    print()
    print("=" * 70)
    print("  OK Tutorial complete! FITS -> NOVA -> FITS conversion demonstrated.")
    print("=" * 70)


if __name__ == "__main__":
    main()
